language: ruby
rvm:
 - 2.2
gemfile:
  - Gemfile
services:
  - postgresql
test:
  adapter: postgresql
  database: Muvin_test
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database Muvin_test;' -U postgres
before_install:
  - gem install nokogiri -- --with-cflags='--std=gnu99'
notifications:
  slack:
    on_success: change
    on_failure: change
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake